spring:
    #    sql:
    #        init:
    #            mode: always
    datasource:
        generate-unique-name: false
        name: OdorPreventionFacility
        hikari:
            driver-class-name: com.mysql.cj.jdbc.Driver
            jdbc-url: jdbc:mysql://localhost:3306/OdorPreventionFacility?connectionTimeZone=Asia/Seoul&allowLoadLocalInfile=true&createDatabaseIfNotExist=true
            username: root
            password:
            connection-test-query: select 1

    web:
        resources:
            static-locations: classpath:/

    jpa:
        hibernate:
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
            ddl-auto: update

server:
    port: 8081

# Debugging logs for Apache Tomcat (uncomment if needed)
#logging:
#  level:
#    org.apache.coyote.http11: DEBUG