spring:
    datasource:
        generate-unique-name: false
        name: OdorPreventionFacility
        hikari:
            driver-class-name: com.mysql.cj.jdbc.Driver
            jdbc-url: jdbc:mysql://localhost:3306/OdorPreventionFacility?connectionTimeZone=Asia/Seoul&allowLoadLocalInfile=true&createDatabaseIfNotExist=true
            username: root
            password: ""
            connection-test-query: select 1
    jpa:
        hibernate:
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
            ddl-auto: update
    web:
        resources:
            static-locations: classpath:/
        servlet:
            encoding:
                charset: UTF-8
                enabled: true
                force: true

server:
    port: 8081
    servlet:
        context-parameters:
            file.encoding: UTF-8
    tomcat:
        uri-encoding: UTF-8

# Debugging logs for Apache Tomcat (uncomment if needed)
#logging:
#  level:
#    org.apache.coyote.http11: DEBUG
